Support local flow path
AtomLinter/linter-flow pull request #180
Opened 2017-09-06 00:46 UTC by stackptr

Basing this off of `linter-eslint` to support a local flow path. Adds `findFlowPath` that accepts the file being linted to find `flow` bin in the corresponding modules directory. Need to ensure it still works with a global installation. There are also most likely edge cases that I do not yet understand as the `linter-eslint` code is complicated in this area

2017-11-15 22:52 UTC, jacobwgillespie commented
I am interested in seeing this merged, as this is the only feature I'm missing from other flow packages.  This package, `linter-flow` is the only flow integration for Atom that supports checking flow as-you-type, which is awesome, however unless the global flow version and the project-local version are exactly the same, running one or the other will cause the flow server to restart since the versions don't match.  Practically that means waiting 15s to run flow when switching between the editor and terminal.

Is there anything I can do to help move this PR forward?

2017-11-16 02:00 UTC, stackptr commented
Hey @jacobwgillespie this has been working fairly stably for me since I submitted this PR. I'm not really sure if there are further contribution requirements that should be met in order to get this merged. You could try to run this locally as well (I simply symlink `~/.atom/packages/linter-flow` to this cloned branch)

2017-12-11 18:59 UTC, stackptr commented
The `flow` binary seems to have some problems when it is spawned multiple times over the course of linting, resulting in CPU locking and other nastiness. I work with an older version of `flow` so I can't speak to whether these problems are fixed currently but I would be interested to know if others would experience this as well. Unfortunately I don't see a fix within scope for this PR

2018-03-26 19:06 UTC, stackptr commented
I am using VSCode these days but am interested in doing what I can to finish this enhancement. Can anyone suggest what my next steps should be?

2018-12-10 21:16 UTC, nmn requested changes
I'm sorry I have been inactive for super super long. I want to merge this, but a few small changes are needed. I will also need to test how everything works after so long.

2018-12-10 21:16 UTC, nmn commented on lib/helpers.js
> +export function check(
I would not change this from a default export to non-default one.

You can still add additional exports while leaving this be the default. I'm trying to minimise breaking changes here.

2018-12-10 21:16 UTC, nmn commented on lib/helpers.js
> +): any {
return type is string. Don't use `any`

2018-12-10 21:16 UTC, nmn commented on lib/index.js
> +import { check, findFlowPath } from './helpers';
Once the check is the default export again, you can use:
`import check, {findFlowPath} from './helpers';`

2018-12-10 21:23 UTC, nmn commented
@amercier You probably stopped caring about this PR since it's already been a year. If that is the case let me know, and I'll do this myself. If you still want this, feel free to update this PR.

2018-12-13 06:41 UTC, amercier commented
@nmn Sorry I didn't author this PR (@stackptr did but, as you said, may not care anymore considering the time). Could you make the changes, please? I (and @hansoksendahl it seems) are still interested :)

2019-01-04 01:03 UTC, nmn commented
I will make the changes for now, although the plugin probably needs a big upgrade to use the LSP support built into Flow directly now.

2019-01-31 02:35 UTC, stackptr commented
I missed the review on this, I can update this PR soon

2019-02-06 07:16 UTC, stackptr commented
Will fix the CI errors soon

2019-02-07 23:23 UTC, stackptr commented
@nmn this should be good now

2021-11-05 01:06 UTC, closed without merging